// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwkx6Qdj_QquWk2e-9VYGPbnIW716Xz18',
    appId: '1:487536047515:web:be694eea047ed32bf59d3e',
    messagingSenderId: '487536047515',
    projectId: 'ecommercy-14aec',
    authDomain: 'ecommercy-14aec.firebaseapp.com',
    storageBucket: 'ecommercy-14aec.firebasestorage.app',
    measurementId: 'G-4QN1L335J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtM14TWvJRP8jOYfBZkiVpHEo7s7NAvvA',
    appId: '1:487536047515:android:35165dd5d33bdd1cf59d3e',
    messagingSenderId: '487536047515',
    projectId: 'ecommercy-14aec',
    storageBucket: 'ecommercy-14aec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhTanBCkjw-LnFpMEis2nsPTvDVpP0WHw',
    appId: '1:487536047515:ios:7c926dc1e296f7cdf59d3e',
    messagingSenderId: '487536047515',
    projectId: 'ecommercy-14aec',
    storageBucket: 'ecommercy-14aec.firebasestorage.app',
    iosBundleId: 'com.example.eCommercy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhTanBCkjw-LnFpMEis2nsPTvDVpP0WHw',
    appId: '1:487536047515:ios:7c926dc1e296f7cdf59d3e',
    messagingSenderId: '487536047515',
    projectId: 'ecommercy-14aec',
    storageBucket: 'ecommercy-14aec.firebasestorage.app',
    iosBundleId: 'com.example.eCommercy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwkx6Qdj_QquWk2e-9VYGPbnIW716Xz18',
    appId: '1:487536047515:web:cd99504aa1202341f59d3e',
    messagingSenderId: '487536047515',
    projectId: 'ecommercy-14aec',
    authDomain: 'ecommercy-14aec.firebaseapp.com',
    storageBucket: 'ecommercy-14aec.firebasestorage.app',
    measurementId: 'G-C8CC4WW0CW',
  );
}
